name: MinVer Calculate
description: Uses the the MinVer tool to calculate the version of your projects.
inputs:
  options:
    description: Options to pass to the MinVer tool.
    required: false
    default: '-i -t v -v i'
outputs:
  version:
    description: The calculated version in SEMVER format.
    value: ${{ steps.minver-calculate.outputs.semver }}
runs:
  using: composite
  steps:
    - id: minver-calculate
      run: |
        semver=$(minver ${{ inputs.options }})
        echo "semver=$semver" >> $GITHUB_OUTPUT
        echo "MINVERVERSIONOVERRIDE=$semver" >> $GITHUB_ENV
      shell: bash
branding:
  icon: 'umbrella'
  color: 'blue'
